### ISSUE TITLE
How does this differ from the react-responsive package?

### ISSUE THREAD

**Issue by JohnAllen** [sportsbet/react-responsive-components#1]
Happy to create a README so others know.  FYI, this is the ~4th ranked result for "react responsive" or something along those lines in Google.

**Comment by att-jamese-sportsbet** [comment]
Looking at react-responsive, it seems to set a listener for every <MediaQuery> component that's created, whereas this one handles the media query listeners in a single <ResponsiveRoot> component at the top level; there will only ever be 4 listeners if 4 breakpoints are set.

This library (react-responsive-components) doesn't cater for orientation or pixel-density type media queries -- only screen width. But hopefully it handles that well.

I've finally added a README and an example.
